#Ordered, Indexed, Mutable, dynamically sized and allows duplicates
l=[]
l=list()
l=[1,2,3,5,4,7,6,2]
print("List: ",l)
print("Access element using index: ",l[4])
print("Access element using negative index: ",l[-2])
print("Index of element: ",l.index(2))
l.append(8)
print("Appending: ",l)
l.extend(['siri',3,5+2j,[1,2,3]])
print("Appending multiple elements: ",l)
l.insert(1,2)
print("Insert in the list: ",l)
l.append("string")
l.append(True)
l.append(3.7)
l.append(2+3j)
l.append((2,3,7,6))
l.append([3,2,5,4,6])
l.append({2,1,5,4})
l.append({'Name':'Siri'})
print("Different type of elements: ",l)
print("Length of list: ",len(l))
l[1]=3
print("Modifying the list elements: ",l)
l.remove(3)
print("Removing value from start: ",l)
print("Remove the last element: ",l.pop())
print("Remove specific index element: ",l.pop(11))
del l[-1]
print("Deleting the specific index and it's memory allocation: ",l)
print("Slicing of list: ",l[-3:])
print("Reverse slicing of list: ",l[-4:-8:-1])
print("Reverse the list without changing list: ",l[::-1],"  ",l)
l.reverse()
print("Reverse the elements in list: ",l)
print("Count of element in list: ",l.count(2))
l.clear()
print("Remove all elements from list: ",l)
l=[2,1,6,3,6,3,5,9,6,7,9,3,5,5,8,3,0]
print("Sort the elements without changing list: ",sorted(l),"   ",l)
l.sort()
print("Sort the elements in the list: ",l)
print("Maximum in the list: ",max(l))
print("Minimum in the list: ",min(l))
print("Sum of elements: ",sum(l))
l.sort(reverse=True)
print("Sort the elements in reverse order: ",l)
l=[2,1,6,3,6,3,5,9,6,7,9,3,5,5,8,3,0]
l=[1,4,2,5,2]
k=l.copy()
k.append(8)
print("Shallow copy: ",k,"  ",l)
m=l
m.append(6)
print("Deep copy: ",m,"   ",l)
l=[1,5,3,5,False,'',[],(),{},set(),0]
print("Any of the elements is ture: ",any(l))
print("All of the elements is ture: ",all(l))