#Ordered, Indexed, Immutable and allows duplicates
t=()
t=tuple()
t=(1,4,4,6,"Siri",'a',True)
print("Tuple: ",t)
print("Access element using index: ",t[3])
print("Access element using negative index: ",t[-2])
print("Index of element: ",t.index(6))
print("Slicing of tuple: ",t[1:4],"    ",t[-4:])
print("Reverse slicing of tuple: ",t[-2:-6:-1])
t1=(1,2,4,5,2,5,{1,4,2,'s'},[5,8,2,5,7],('a','b','c'),{'Name':"Siri"},3.7,4+5j)
t2=('aid',"Siri",True,[],{},(),set())
print("Concatenation of tuples: ",t1+t2)
print("Repetition of tuple: ",t*4)
print("Membership of tuple: ",1 in t,"  ",2 in t)
t=(1,5,2)
a,b,c=t
print("Tuple unpacking: ",a,"   ",b,"   ",c)
t=(1,4,2,5,2,5,2,6,2,7,9,5,8,0)
print("Count of element in tuple: ",t.count(2))
print("Length of tuple: ",len(t))
print("Maximum in the tuple: ",max(t))
print("Minimum in the tuple: ",min(t))
print("Sum of elements: ",sum(t))